name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push containers
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zastrix/spigot-builder:openjdk-8-alpine
            zastrix/spigot-builder:openjdk-16-alpine
            zastrix/spigot-builder:openjdk-17-alpine
          dockerfile: |
            Dockerfile8
            Dockerfile16
            Dockerfile17
